name: release-artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_the_mod:
    name: Publish To Modrinth and GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Read properties from gradle.properties
        id: read_properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: minecraft_version mod_version

      - name: Build artifacts
        run: ./gradlew clean build

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: Redstonery Mod ${{ steps.read_properties.outputs.mod_version }} for Minecraft ${{ steps.read_properties.outputs.minecraft_version }}
          version: mc${{ steps.read_properties.outputs.minecraft_version }}-${{ steps.read_properties.outputs.mod_version }}
          version-type: alpha
          changelog-file: CHANGELOG_NEWEST.md

          modrinth-id: JGYH59f7
          modrinth-token: ${{ secrets.TOKEN_MODRINTH }}

          github-token: ${{ secrets.TOKEN_GITHUB }}

